# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinaryPython36', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
