# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinaryPython36', '0002_auto_20170213_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='top_image',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
