# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordinaryPython36', '0005_auto_20170214_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordinaryPython36.Feed'),
        ),
    ]
