# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinaryPython36', '0007_similararticlelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
