# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordinaryPython36', '0009_auto_20170313_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default='')),
                ('top_image', models.URLField(max_length=2000, null=True)),
                ('title', models.TextField(default='')),
                ('date', models.DateField(null=True)),
                ('text', models.TextField(default='')),
                ('summary', models.TextField(default='')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordinaryPython36.Feed')),
            ],
        ),
    ]
