# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinaryPython36', '0010_articletrain'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
