# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinaryPython36', '0012_auto_20170316_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(default='', max_length=2000),
        ),
    ]
