# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 11:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordinaryPython36', '0016_userarticleinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='similar_users',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
