# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordinaryPython36', '0017_userprofile_similar_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSimilarityInCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_ratio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserToCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordinaryPython36.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='similar_users',
        ),
        migrations.AddField(
            model_name='usertocategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordinaryPython36.UserProfile'),
        ),
        migrations.AddField(
            model_name='usersimilarityincategory',
            name='similar_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordinaryPython36.UserProfile'),
        ),
        migrations.AddField(
            model_name='usersimilarityincategory',
            name='user_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordinaryPython36.UserToCategory'),
        ),
    ]
