# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 16:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinaryPython36', '0018_auto_20170408_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersimilarityincategory',
            name='similarity_ratio',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
