# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordinaryPython36', '0019_auto_20170408_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='added_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ordinaryPython36.UserProfile'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ordinaryPython36.Category'),
        ),
    ]
