# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordinaryPython36', '0020_auto_20170419_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articletrain',
            name='feed',
        ),
        migrations.DeleteModel(
            name='ArticleTrain',
        ),
    ]
