# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordinaryPython36', '0021_auto_20170422_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_removed', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_removed', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_removed', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelPublisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_removed', models.DateTimeField(null=True)),
                ('following_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordinaryPython36.Channel')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordinaryPython36.Publisher')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=100)),
                ('description', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_removed', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_removed', models.DateTimeField(null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordinaryPython36.Article')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordinaryPython36.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='OfflineArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_offlined', models.DateTimeField(auto_now_add=True)),
                ('date_removed', models.DateTimeField(null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordinaryPython36.Article')),
            ],
        ),
        migrations.CreateModel(
            name='TagChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_removed', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feed',
            name='name',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userarticleinteraction',
            name='date_accessed',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='offlinearticle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordinaryPython36.UserProfile'),
        ),
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordinaryPython36.UserProfile'),
        ),
        migrations.AddField(
            model_name='channelfeed',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordinaryPython36.Feed'),
        ),
        migrations.AddField(
            model_name='channelfeed',
            name='following_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordinaryPython36.Channel'),
        ),
        migrations.AddField(
            model_name='channelcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordinaryPython36.Category'),
        ),
        migrations.AddField(
            model_name='channelcategory',
            name='following_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordinaryPython36.Channel'),
        ),
        migrations.AddField(
            model_name='channel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordinaryPython36.UserProfile'),
        ),
    ]
