# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordinaryPython36', '0022_auto_20170422_1725'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagChannel',
        ),
    ]
