# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinaryPython36', '0026_auto_20170512_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userarticleinteraction',
            name='date_accessed',
            field=models.DateTimeField(),
        ),
    ]
